# randrange를 활용한 다섯개 난수 발생
import random

for i in range(5) :
    print(f"number : {random.randrange(1, 101)}")